const races = {
    1: 'Human',
    2: 'Orc',
    3: 'Dwarf',
    4: 'Night Elf',
    5: 'Undead',
    6: 'Tauren',
    7: 'Gnome',
    8: 'Troll',
    10: 'Blood Elf',
    11: 'Draenei',
    22: 'Worgen',
    24: 'Goblin',
    25: 'Pandaren',
    26: 'Nightborne',
    27: 'Highmountain Tauren',
    28: 'Void Elf',
    29: 'Lightforged Draenei',
    30: 'Dark Iron Dwarf',
    31: 'Maghar Orc',
    32: 'Kul Tiran',
    33: 'Zandalari Troll',
};

const classes = {
    1: 'Warrior',
    2: 'Paladin',
    3: 'Hunter',
    4: 'Rogue',
    5: 'Priest',
    6: 'Death Knight',
    7: 'Shaman',
    8: 'Mage',
    9: 'Warlock',
    10: 'Monk',
    11: 'Druid',
    12: 'Demon Hunter',
};

export { races, classes };